@startuml proxy
!theme plain
skinparam linetype ortho

class Client

interface RouteService <<interface>> {
  getRoute(start: string, end: string, mobility: string, type: string): Route
}

class RouteProxy{
  - realService: OpenRouteService
  - cache: Map<string, Route>
  + getRoute(start: string, end: string, mobility: string, type: string): Route
  + calculateAndSaveOtherTypesRoutesOnCache(start: string, end: string, mobility: string, type: string): void
}

class OpenRouteService{
  + getRoute(start: string, end: string, mobility: string, type: string): Route 
}


' Realizaciones (implementación de la interfaz)
RouteService <|.. RouteProxy
RouteService <|.. OpenRouteService

' Agregación: Proxy tiene referencia a Service
RouteProxy o--> OpenRouteService

Client -> RouteService


@enduml

